# Generated by Django 4.2.3 on 2023-08-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0003_remove_client_comment_alter_logs_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('running', 'запущена'), ('completed', 'завершена')], default='created', max_length=10, verbose_name='статус'),
        ),
    ]
