# Generated by Django 4.2.4 on 2023-09-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0005_remove_spam_messages_spam_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='post_answer',
        ),
        migrations.AddField(
            model_name='logs',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='logs',
            name='errors',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ошибки отправки'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='spam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spam.spam', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(choices=[('ок', 'успешно'), ('failed', 'ошибка')], verbose_name='статус последней рассылки'),
        ),
        migrations.AlterField(
            model_name='spam',
            name='clients',
            field=models.ManyToManyField(to='spam.client', verbose_name='адресаты рассылки'),
        ),
        migrations.AlterField(
            model_name='spam',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spam',
            name='periodicity',
            field=models.SmallIntegerField(default=1, verbose_name='периодичность рассылки (дней)'),
        ),
        migrations.AlterField(
            model_name='spam',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('started', 'запущена'), ('completed', 'завершена')], default='created', max_length=10, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='spam',
            name='title',
            field=models.CharField(default='Рассылка_<django.db.models.fields.BigAutoField>', max_length=15, verbose_name='Название'),
        ),
    ]
