# Generated by Django 4.2.4 on 2023-09-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0007_alter_spam_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam',
            name='title',
            field=models.CharField(default='Рассылка_<property object at 0x0000014DCF952D60>', max_length=50, verbose_name='Название'),
        ),
    ]
