# Generated by Django 4.2.4 on 2023-09-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0008_alter_spam_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spam',
            name='title',
            field=models.CharField(default='Рассылка_<django.db.models.fields.AutoField>', max_length=50, verbose_name='Название'),
        ),
    ]
