# Generated by Django 4.2.4 on 2023-09-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0010_alter_spam_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spam',
            name='title',
            field=models.CharField(default='Рассылка ', max_length=50, verbose_name='Название'),
        ),
    ]
