# Generated by Django 4.2.4 on 2023-09-08 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spam', '0012_alter_logs_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='spam',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор рассылки'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='errors',
            field=models.CharField(max_length=100, verbose_name='ошибки отправки'),
        ),
    ]
