# Generated by Django 4.2.4 on 2023-09-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_clients', '0001_initial'),
        ('spam', '0015_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam',
            name='spam_clients',
            field=models.ManyToManyField(to='spam_clients.client', verbose_name='адресаты рассылки'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
