# Generated by Django 4.2.4 on 2023-09-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_clients', '0001_initial'),
        ('spam', '0016_alter_spam_clients_delete_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='spam',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='spam',
            name='spam_clients',
        ),
        migrations.AddField(
            model_name='spam',
            name='clients',
            field=models.ManyToManyField(to='spam_clients.client', verbose_name='адресаты рассылки'),
        ),
    ]
